import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  backgroundImage: {
    flex: 1,
    resizeMode: "stretch", // or 'stretch'
  },
  flexrow: {
    flexDirection: "row",
  },
  container: {
    flex: 1,
    justifyContent: "center",
    paddingTop: 100,
    backgroundColor: "#e1e5e8",
    padding: 8,
    alignItems: "center",
  },
  containerImageBackground: {
    flex: 1,
    justifyContent: "center",
  },
  image: {
    flex: 1,
    resizeMode: "cover",
    justifyContent: "center",
    alignItems: "center",
    paddingBottom: 50,
  },
  textWithShadow: {
    color: "#fff",
    textShadowColor: "grey",
    fontFamily: "Montserrat",
    justifyContent: "center",
    fontSize: 40,
    fontWeight: "bold",
    textAlign: "center",
    textShadowOffset: { width: 10, height: 5 },
    textShadowRadius: 18,
  },
  card: {
    width: "80%",
    backgroundColor: "white",
    borderRadius: 15,
    elevation: 10,
    padding: 20,
    marginBottom: 15,
  },
  cardOpacity: {
    opacity: 0.9,
    width: "80%",
    backgroundColor: "white",
    borderRadius: 15,
    elevation: 10,
    padding: 20,
    marginBottom: 15,
  },
  cardOpacityIcon: {
    height: 50,
    justifyContent: "center",
    alignItems: "center",
    opacity: 0.9,
    width: 50,
    backgroundColor: "white",
    borderRadius: 25,
    elevation: 2,
  },
  cardScrollable: {
    width: "100%",
    backgroundColor: "white",
    borderRadius: 15,
    elevation: 10,
    padding: 15,
  },
  profileImg: {
    width: 30,
    height: 30,
    borderRadius: 50,
    marginRight: 10,
  },
  header: {
    fontFamily: "Montserrat",
    alignItems: "center",
    textAlign: "center",
    alignContent: "center",
    flexDirection: "row",
    //paddingBottom: 10,
    borderBottomColor: "gray",
    borderStyle: "dashed",
    borderBottomWidth: 1,
    marginBottom: 10,
    fontWeight: "bold",
    //fontSize: 24,
  },
  headingTop: {
    position: "absolute",
    justifyContent: "center",
    top: "3%",
  },
  headerCard: {
    fontFamily: "Rubik",
    fontWeight: "bold",
    fontSize: 22,
    justifyContent: "center",
  },
  startBtn: {
    backgroundColor: "#90bdff",
    borderRadius: 50,
    padding: 10,
    width: "80%",
    alignItems: "center",
    marginTop: 20,
  },
  startText: {
    color: "white",
  },
  headerDramatic: {
    fontFamily: "Montserrat",
    justifyContent: "center",
    fontSize: 40,
    fontWeight: "bold",
    //marginBottom: 5,
    textAlign: "center",
  },
  description: {
    fontFamily: "Rubik",
    fontSize: 14,
    color: "gray",
    padding: 5,
  },
  descriptionBullets: {
    fontFamily: "Rubik",
    fontSize: 14,
    color: "gray",
    paddingBottom: 2,
    paddingLeft: 5,
    marginLeft: 10,
  },
  scrollView: {
    marginTop: 100,
    marginRight: 40,
    marginLeft: 40,
  },
});
